### PR TITLE
make sleep reliable by measuring how long we actually slept

### PR DESCRIPTION
**Pull request by grosser**
@adammw @riywo 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by grosser** [comment]
test failure seems unrelated

**Comment by riywo** [comment]
Hi,

Thank you for your commit. As your comment in the code, is it still unreliable even if we merge this commit?

Also, did you look into how AWS SDK for Ruby handle similar situation?

**Comment by grosser** [comment]
it is reliable with this commit, I did not find any other part where this happens ... this is all pretty old now and we have migrated away from fluentd in the last month, so I can't test/reproduce this anymore

**Comment by riywo** [comment]
Got it. Thank you for your reply.

**Comment by simukappu** [comment]
Closing this PR for now. Please reopen if required. Thank you!

**Comment by simukappu** [comment]
Reopened to make test this more reliable sleep along with enhancement of batch request monitoring.

**Review by simukappu — APPROVED** [review]

**Pull request merged**
