### PR TITLE
Support PutRecords API

### PR DESCRIPTION
**Pull request by winebarrel**
Support [PutRecords](http://docs.aws.amazon.com/sdkforruby/api/Aws/Kinesis/Client.html#put_records-instance_method) API.

Please merge if there is no problem :smiley_cat:

### CODE REVIEW

**Comment by imaifactory** [comment]
Hi, thank you for waiting on this PR to be accepted.
@winebarrel : Can you rebase your changes to single commit please? Also please confirm this contribution is released under Apache 2.0.

@az3 @jkugiya : We are adding some changes regarding record count limitation on this PR. Thank you for clarification.

**Comment by winebarrel** [comment]
> Can you rebase your changes to single commit please? 

done :smile: 

>  Also please confirm this contribution is released under Apache 2.0.

It's all right.

**Comment by imaifactory** [comment]
Thank you! Please wait a bit more.

**Comment by imaifactory** [comment]
@winebarrel Thank you for the contribution and waiting! Merged.

**Pull request merged**
