### PR TITLE
#203: add placeholder support to delivery_stream_name for kinesis_firehose. closes #203

### LINKED ISSUE #203: Add placeholder support for the stream name with kinesis_firehose (too)
https://github.com/awslabs/aws-fluent-plugin-kinesis/pull/174 added support for placeholders to `kinesis_streams` and `kinesis_streams_aggregated` types. It would be nice to see support added for `kinesis_firehose` type as well.

### PR DESCRIPTION
**Pull request by clcpolevaulter**
Issue #203

This is heavily based off the changes to #174. Placeholders are now supported in firehose streams. 

⚠️ I won't claim to know the best way to test this but all the test do pass. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by clcpolevaulter** [comment]
Any updates on this?

**Comment by clcpolevaulter** [comment]
Any updates on this request?

**Comment by clcpolevaulter** [comment]
@simukappu ::

I have updated the README as requested.

**Comment by simukappu** [comment]
Please wait a moment as we are going on the process.

**Comment by simukappu** [comment]
Merged and published as v3.2.3. Thank you for your contribution!
https://rubygems.org/gems/fluent-plugin-kinesis/versions/3.2.3

**Pull request merged**
