### PR TITLE
Don't chomp formatted messages. Fixes #142

### LINKED ISSUE #142: chomp is removing trailing newlines.
https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/lib/fluent/plugin/kinesis.rb#L108

Here, the additional formatting - chomp - is causing newlines to be removed that the JSON formatter is adding by default. I think at this point we should rely on the formatter and not do any post-processing.

### PR DESCRIPTION
**Pull request by geofffranks**
Signed-off-by: David Bishop <dbisj@allstate.com>

### CODE REVIEW

**Comment by burkaygur** [comment]
any chance we can prioritize this @riywo ?

**Comment by cynipe** [comment]
having the same trouble. is there any chance?

**Comment by fujiwara** [comment]
@riywo Please confirm this or consider to delegate to an active maintainer. 🙏

**Comment by riywo** [comment]
Sorry for our late response. The team is prioritizing this, so please add use cases when you need it.

@geofffranks , please comfirm the usage of this contribution by adding the statement from this template. https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by geofffranks** [comment]
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

**Comment by riywo** [comment]
@geofffranks Thank you for your confirming.

@fujiwara @cynipe @burkaygur in case you have not been notified, please post your use cases here for us to understand the issue properly. Probably we can use this issue for your feedback: https://github.com/awslabs/aws-fluent-plugin-kinesis/issues/142

**Comment by cynipe** [comment]
same as @fujiwara. Actually, mine is json though.

**Comment by burkaygur** [comment]
Same use case as @cynipe.

**Comment by riywo** [comment]
Thank you for your use cases.

Just released v3.0.0.rc.2.0 which doesn't `chomp` by default. Please try it out and give us feedback! https://rubygems.org/gems/fluent-plugin-kinesis/versions/3.0.0.rc.2.0

**Comment by cynipe** [comment]
@riywo  Just tried it out.
For me, v3.0.0.rc.2.0 works like a charm 🎉

**Comment by burkaygur** [comment]
Whats the timeline for 3.0.0 release @riywo ? Tried and works great.

**Comment by simukappu** [comment]
@burkaygur We will publish v3.0.0 next week unless we get any trouble feedback. We are appreciate your patience.

**Comment by simukappu** [comment]
This PR changes have been already merged into master branch as v3.0.0.rc.2.0. I will close this PR and let's move to #142.

**Pull request closed without merging**
