### PR TITLE
Add option use_yajl for avoid UndefinedConversionError

### PR DESCRIPTION
**Pull request by tamtam180**
I want to use Yajl instead of JSON, 
because to_json method raise error when receive multibyte text.

So, I tried implemented #13
Please check this patch :bow:

### CODE REVIEW

**Comment by imaifactory** [comment]
@tamtam180 
Really appreciate for this. I will look into this.

**Comment by imaifactory** [comment]
@tamtam180 
Sorry, one question first: Can you confirm that these changes are provided under Apache License 2.0?

**Comment by tamtam180** [comment]
> provided under Apache License 2.0?

Sure!

(and I fixed typo: yagl -> yajl)

**Comment by imaifactory** [comment]
Changes are looks good to me. I will push this to the next pipeline.

**Comment by imaifactory** [comment]
@tamtam180 
Thank you for contribution! Please wait gem release. I will inform you here.

**Comment by imaifactory** [comment]
@tamtam180 
Thank you for waiting. We have pushed to RubyGems.org. https://rubygems.org/gems/fluent-plugin-kinesis/versions/0.3.4

**Pull request merged**
