### PR TITLE
[WIP] New version: Firehose and KPL / Refactor / Tests

### PR DESCRIPTION
**Pull request by riywo**
This branch is a RC for v1.0.0 of the plugin. You can try the latest RC version with following command:

    gem install fluent-plugin-kinesis --pre

If you use td-agent, follow the command:

    td-agent-gem install fluent-plugin-kinesis --pre

I'd like to get some feedback, please comment here.

Thanks to @winebarrel because my firehose plugin is based on [his plugin](https://github.com/winebarrel/fluent-plugin-kinesis-firehose).

Note: License has changed to Amazon Software License.

### CODE REVIEW

**Comment by winebarrel** [comment]
:+1:

**Comment by otaki-ryuta** [comment]
:+1:

**Comment by kzk** [comment]
heads up for @wryun, who developed fluent-plugin-kinesis-aggregate

**Comment by riywo** [comment]
I'll rebase this branch for releasing v1.0.0 and send another PR.

**Pull request closed without merging**
