### PR TITLE
Don't log if record is nil

### PR DESCRIPTION
**Pull request by sasso**

### CODE REVIEW

**Comment by riywo** [comment]
Hi @sasso ,

Thank you for your PR. Could you add an test for this fix?

Also, could you confirm that we can use, modify, copy, and redistribute this contribution?

Best,

**Comment by sasso** [comment]
I confirm that you can use, modify, copy, and redistribute this contribution!

**Comment by riywo** [comment]
Thanks! I'll merge this and release patch update.

**Comment by riywo** [comment]
I'm checking the behavior but I can pass your test unless applying your patch.

What is your expectation? What is your original issue?

**Comment by riywo** [comment]
Hi @sasso ,

Could you give me more information I mentioned the comment above?

Best,

**Comment by riywo** [comment]
Closing. If you are facing this issue, please add more comment.

**Pull request closed without merging**
