### PR TITLE
Add proxy support for fluentd kinesis plugin

### PR DESCRIPTION
**Pull request by trongnhanbmt**
Sometime we need to go through proxy.

### CODE REVIEW

**Comment by imaifactory** [comment]
Thanks @trongnhanbmt , I will look into this.

**Comment by imaifactory** [comment]
@trongnhanbmt 
Can you confirm that this change is provided under Apache License 2.0?

**Comment by trongnhanbmt** [comment]
@imaifactory 
Yes. I confirmed.

**Comment by imaifactory** [comment]
We will update rubygem.

**Comment by trongnhanbmt** [comment]
Thanks a lot @imaifactory.

**Pull request merged**
