### PR TITLE
#27 - use STS:AssumeRole to get auto-refreshing credentials

### PR DESCRIPTION
**Pull request by jtblin**
@imaifactory as discussed in #27. I haven't been able to perform end-to-end testing yet (I added a unit test) but just wanted to push in case you have early feedback.

### CODE REVIEW

**Comment by imaifactory** [comment]
@jtblin This is great, thanks! Please ping me once you finished your end-to-end test. Also I will do my end-to-end test.

**Comment by Jackyjjc** [comment]
I did an end-to-end test with this and it works.

**Comment by jtblin** [comment]
Awesome, thanks @Jackyjjc! @imaifactory, Jacky and I work together, so it should be good to go now.

**Comment by imaifactory** [comment]
@jtblin @Jackyjjc 

Thank you for clarification! I found one point which I want you to update.
In some case, we need to accept and pass `external_id` for assuming role from 3rd party AWS account.

http://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html
http://docs.aws.amazon.com/sdkforruby/api/Aws/AssumeRoleCredentials.html#initialize-instance_method

So, it should be like this?

## config
```
<match kinesis.spark>
    type kinesis
    stream_name crossaccount_stream
    region ap-northeast-1
    flush_interval 1
    random_partition_key
    role_arn CROSS_ACCOUNT_ROLE_ARN
    external_id SOME_EXTERNAL_ID
</match>
```

## code
```ruby
config_param :role_arn,         :string, :default => nil
config_param :external_id,      :string, :default => nil

# snip

elsif @role_arn
    credentials = Aws::AssumeRoleCredentials.new(
      client: Aws::STS::Client.new(options),
      role_arn: @role_arn,
      role_session_name: "aws-fluent-plugin-kinesis",
      duration_seconds: 60 * 60,
      external_id: @external_id
    )
    options[:credentials] = credentials
end

```

Thanks!

**Comment by imaifactory** [comment]
BTW, I have done end-to-end testing successfully. So I can merge your PR when it's updated as I mentioned above.

Much appreciated :)

**Comment by jtblin** [comment]
Done :)

**Comment by imaifactory** [comment]
Thanks!! Please kindly wait for a while. I push this to the pipeline.

**Comment by imaifactory** [comment]
@jtblin Can you confirm that your changes are provided under Apache License 2.0.? Thank you.

**Comment by jtblin** [comment]
Yes I confirm that my changes are provided under Apache License 2.0.

**Comment by imaifactory** [comment]
Thanks for confirmation, please wait for a while.

**Comment by imaifactory** [comment]
@jtblin @Jackyjjc 
Thank you for your contribution, the PR is merged.
Followingly I will add README fix today, and I will push it to RubyGems.(It may take several days.)

**Pull request merged**
